language: go
go:
 - 1.6

services:
  - redis-server

script:
# - go get -u github.com/evolsnow/gpns
 - go build -o rpc github.com/evolsnow/gpns
 - ./rpc -c $HOME/gopath/src/github.com/evolsnow/gpns/*.json &
 - go build -o testServer .
 - ./testServer -c config.json.example &
 - go test -v ./...
 - killall testServer
 - killall rpc