language: go
go:
 - 1.6

services:
  - redis-server

script:
 - go get -t ./...
 - go build -o rpc ./gpns
 - ./rpc &
 - go build -o testServer .
 - ./testServer -c config.json.example &
 - go test -v ./...
 - killall testServer
 - killall rpc