// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	PushRequest
	PushReply
	MailRequest
	MailResponse
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Age     int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Push request, containing push message and repeated device token
type PushRequest struct {
	Message     string            `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	DeviceToken []string          `protobuf:"bytes,2,rep,name=deviceToken" json:"deviceToken,omitempty"`
	ExtraInfo   map[string]string `protobuf:"bytes,3,rep,name=extraInfo" json:"extraInfo,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *PushRequest) Reset()                    { *m = PushRequest{} }
func (m *PushRequest) String() string            { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()               {}
func (*PushRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PushRequest) GetExtraInfo() map[string]string {
	if m != nil {
		return m.ExtraInfo
	}
	return nil
}

// Push response, containing numbers of successful push and failed token list
type PushReply struct {
	Count       int32    `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	DeviceToken []string `protobuf:"bytes,2,rep,name=deviceToken" json:"deviceToken,omitempty"`
}

func (m *PushReply) Reset()                    { *m = PushReply{} }
func (m *PushReply) String() string            { return proto.CompactTextString(m) }
func (*PushReply) ProtoMessage()               {}
func (*PushReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// Send mail request
type MailRequest struct {
	To      string `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Subject string `protobuf:"bytes,3,opt,name=subject" json:"subject,omitempty"`
	Body    string `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
}

func (m *MailRequest) Reset()                    { *m = MailRequest{} }
func (m *MailRequest) String() string            { return proto.CompactTextString(m) }
func (*MailRequest) ProtoMessage()               {}
func (*MailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// Send mail response{
type MailResponse struct {
}

func (m *MailResponse) Reset()                    { *m = MailResponse{} }
func (m *MailResponse) String() string            { return proto.CompactTextString(m) }
func (*MailResponse) ProtoMessage()               {}
func (*MailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*HelloRequest)(nil), "protos.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "protos.HelloReply")
	proto.RegisterType((*PushRequest)(nil), "protos.PushRequest")
	proto.RegisterType((*PushReply)(nil), "protos.PushReply")
	proto.RegisterType((*MailRequest)(nil), "protos.MailRequest")
	proto.RegisterType((*MailResponse)(nil), "protos.MailResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Samaritan service

type SamaritanClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Apple Push
	ApplePush(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushReply, error)
	// Mail send
	SendMail(ctx context.Context, in *MailRequest, opts ...grpc.CallOption) (*MailResponse, error)
}

type samaritanClient struct {
	cc *grpc.ClientConn
}

func NewSamaritanClient(cc *grpc.ClientConn) SamaritanClient {
	return &samaritanClient{cc}
}

func (c *samaritanClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/protos.Samaritan/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *samaritanClient) ApplePush(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushReply, error) {
	out := new(PushReply)
	err := grpc.Invoke(ctx, "/protos.Samaritan/ApplePush", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *samaritanClient) SendMail(ctx context.Context, in *MailRequest, opts ...grpc.CallOption) (*MailResponse, error) {
	out := new(MailResponse)
	err := grpc.Invoke(ctx, "/protos.Samaritan/SendMail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Samaritan service

type SamaritanServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// Apple Push
	ApplePush(context.Context, *PushRequest) (*PushReply, error)
	// Mail send
	SendMail(context.Context, *MailRequest) (*MailResponse, error)
}

func RegisterSamaritanServer(s *grpc.Server, srv SamaritanServer) {
	s.RegisterService(&_Samaritan_serviceDesc, srv)
}

func _Samaritan_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SamaritanServer).SayHello(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Samaritan_ApplePush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SamaritanServer).ApplePush(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Samaritan_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(MailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SamaritanServer).SendMail(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Samaritan_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Samaritan",
	HandlerType: (*SamaritanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Samaritan_SayHello_Handler,
		},
		{
			MethodName: "ApplePush",
			Handler:    _Samaritan_ApplePush_Handler,
		},
		{
			MethodName: "SendMail",
			Handler:    _Samaritan_SendMail_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x52, 0xcb, 0x4e, 0xeb, 0x30,
	0x10, 0x6d, 0xfa, 0xb8, 0x97, 0x4c, 0xaa, 0x0a, 0x4c, 0x17, 0x51, 0x56, 0x95, 0x57, 0xac, 0xba,
	0x28, 0xaf, 0x0a, 0xb1, 0x00, 0xa1, 0x4a, 0x20, 0x84, 0x84, 0x52, 0x7e, 0xc0, 0x4d, 0x07, 0x28,
	0x4d, 0xed, 0x10, 0x3b, 0x15, 0xf9, 0x2e, 0xbe, 0x82, 0xbf, 0xc2, 0x8e, 0x13, 0x35, 0x45, 0x45,
	0xac, 0x32, 0xaf, 0xe3, 0x33, 0xe7, 0x4c, 0xc0, 0x4d, 0x93, 0x68, 0x98, 0xa4, 0x42, 0x09, 0xf2,
	0xaf, 0xf8, 0x48, 0x7a, 0x02, 0xdd, 0x5b, 0x8c, 0x63, 0x11, 0xe2, 0x7b, 0x86, 0x52, 0x11, 0x02,
	0x6d, 0xce, 0x56, 0xe8, 0x3b, 0x03, 0xe7, 0xc8, 0x0d, 0x8b, 0x98, 0xec, 0x43, 0x8b, 0xbd, 0xa0,
	0xdf, 0xd4, 0xa5, 0x4e, 0x68, 0x42, 0x3a, 0x06, 0x28, 0x51, 0x49, 0x9c, 0x13, 0x1f, 0xfe, 0xaf,
	0x50, 0x4a, 0x33, 0x63, 0x61, 0x55, 0xba, 0x03, 0xf9, 0xe5, 0x80, 0xf7, 0x98, 0xc9, 0xd7, 0x8a,
	0xef, 0x77, 0xec, 0x00, 0xbc, 0x39, 0xae, 0x17, 0x11, 0x3e, 0x89, 0x25, 0x72, 0xfd, 0x46, 0x4b,
	0x77, 0xeb, 0x25, 0x72, 0x05, 0x2e, 0x7e, 0xa8, 0x94, 0xdd, 0xf1, 0x67, 0xe1, 0xb7, 0x74, 0xdf,
	0x1b, 0x51, 0x2b, 0x4f, 0x0e, 0x6b, 0x1c, 0xc3, 0x49, 0x35, 0x34, 0xe1, 0x2a, 0xcd, 0xc3, 0x0d,
	0x28, 0xb8, 0x84, 0xde, 0x76, 0xd3, 0x6c, 0xbc, 0xc4, 0xbc, 0xdc, 0xc5, 0x84, 0xa4, 0x0f, 0x9d,
	0x35, 0x8b, 0x33, 0xab, 0xc2, 0x0d, 0x6d, 0x72, 0xd1, 0x1c, 0x3b, 0xf4, 0x06, 0x5c, 0x4b, 0x63,
	0x4c, 0xd0, 0x63, 0x91, 0xc8, 0xb8, 0x2a, 0xa0, 0x9d, 0xd0, 0x26, 0x7f, 0x8b, 0xa0, 0xf7, 0xe0,
	0x3d, 0xb0, 0x45, 0x5c, 0xf9, 0xd1, 0x83, 0xa6, 0x12, 0x25, 0x95, 0x8e, 0x8c, 0x3f, 0x32, 0x9b,
	0xbd, 0x61, 0xa4, 0xb4, 0xc2, 0xc2, 0x9f, 0x32, 0x35, 0x97, 0x9a, 0x89, 0x79, 0xee, 0xb7, 0xed,
	0xa5, 0x4c, 0x4c, 0x7b, 0xd0, 0xb5, 0x8f, 0xc9, 0x44, 0x70, 0x89, 0xa3, 0x4f, 0x07, 0xdc, 0x29,
	0x5b, 0xb1, 0x74, 0xa1, 0x18, 0x27, 0x67, 0xb0, 0x37, 0x65, 0x79, 0x71, 0x38, 0xd2, 0xaf, 0x8c,
	0xaa, 0x5f, 0x3f, 0x20, 0x3f, 0xaa, 0x5a, 0x18, 0x6d, 0x90, 0x53, 0x70, 0xaf, 0x93, 0x24, 0x46,
	0x23, 0x96, 0x1c, 0xee, 0x70, 0x38, 0x38, 0xd8, 0x2e, 0x5a, 0xd8, 0xb9, 0xa6, 0x43, 0x3e, 0x37,
	0x0b, 0x6d, 0x50, 0x35, 0xad, 0x41, 0x7f, 0xbb, 0x68, 0x77, 0xa6, 0x8d, 0x99, 0xfd, 0x37, 0x8f,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x05, 0xf7, 0x65, 0xaf, 0x02, 0x00, 0x00,
}
